title: Jack Dean # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Financial Engineering Master's Candidate and Research Analyst at Millennium   
  <br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/jack-dean-445336150/">LinkedIn</a> 
  <br>
  <a href="https://github.com/jdean53/covid_event_study/blob/master/Jack%20Dean%20Resume%200122.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/jdean53/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
